# Generated by Django 6.0.7 on 2026-07-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubwayStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('borough', models.CharField(max_length=50)),
                ('routes', models.CharField(max_length=100)),
                ('transfers', models.CharField(blank=True, max_length=100)),
                ('express', models.BooleanField(default=False)),
            ],
        ),
    ]
